inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - app/controllers/**
    - app/models/**
    - app/controllers/**
    - app/helpers/**
  Exclude:
    - db/**
    - config/**
    - script/**

